server:
  port: 8181
  servlet:
    encoding:
      charset: UTF-8

spring:
  application:
    name: security-jwt
  main:
    allow-circular-references: true #允许循环依赖
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security_jwt?
      serverTimezone=Asia/Shanghai
      &useUnicode=true
      &characterEncoding=utf8
      &useSSL=true
    username: root
    password: root

mybatis-plus:
  type-aliases-package: work.pcdd.securityjwt.model.entity.*
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  # JWT加密使用的密钥
  secret: N8eAgGj@qfJ!N9J8
  # 存储JWT的请求头
  token-name: Authorization
  # JWT负载中拿到开头
  token-prefix: Bearer
  # JWT的有效期（单位秒，60*60*24 1天）
  expire: 86400
